name: ci
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4
      - name: Build 
        run: docker build -t test-image .
      - name: Run
        run: docker run --rm -d -p 8000:8000 --name test-container test-image
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install pytest
      - name: Tests
        run: |
          RUNNING_STATE=$(docker inspect -f '{{.State.Running}}' test-container)
          echo "Container state: $RUNNING_STATE"
          if [ "$RUNNING_STATE" == "true" ]; then
            echo "Container is running."
          else
            echo "Container is not running."
            exit 1
          fi
          python3 -m pytest tests.py
          sudo docker stop test-container
      - name: Bump version and push the tag
        id: tag_action
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: 1.0.0
          WITH_V: false
          DEFAULT_BUMP: patch
          DRY_RUN: false

      - name: Set tag version as environment variable
        run: echo "TAG_VERSION=${{ steps.bump_version.outputs.new_tag }}" >> $GITHUB_ENV
          
      
